
#pragma once

enum DSK_ERROR_CODES {
    DSK_FILE_ERROR = -1,
    DSK_OK = 0,
    DSK_UNKNOWN_FORMAT,
    DSK_UNSUPPORTED_FORMAT,
    DSK_TOO_LARGE,
    DSK_MALFORMED_TRACK_INFO,
    DSK_UNEXPECTED_TRACK,
    DSK_UNEXPECTED_SIDE,
    DSK_UNEXPECTED_SECTOR_SIZE,
    DSK_UNEXPECTED_SECTOR_NUMBER,
};

int dsk2dir(const char* path);
int dir2dsk(const char* path);
